from django.urls import path
from deals_app.views import (
    AdminCategoryAPIView,
    ApproveCompanyAPIView,
    CompanyCurrentUserAPIView,
    CompanyDashboardAPIView,
    AdminCompanyListCreateAPIView,
    AdminCompanyDetailAPIView,
    AdminFlyerListAPIView,
    AdminProductListAPIView,
    AdminProfileAPIView,
    AdminUserDetailAPIView,
    AdminUserListCreateAPIView,
    AppSettingsAPIView,
    CategoryDetailAPIView,
    CompanyFlyerCreateAPIView,
    CompanyFlyerDeleteAPIView,
    CompanyFlyerListAPIView,
    CompanyFlyerReviewsAPIView,
    CompanyFlyerToggleAPIView,
    CompanyFlyerUpdateAPIView,
    CompanyProductDeleteAPIView,
    CompanyProductListAPIView,
    CompanyProductListCreateAPIView,
    CompanyProductToggleAPIView,
    CompanyProductUpdateAPIView,
    CompanyProfileUpdateAPIView,
    CompanyRequestCreateAPIView,
    CompanyRequestListAPIView,
    CurrentUserAPIView,
    DeleteFlyerAPIView,
    DeleteProductAPIView,
    HomePageAPIView,
    AdminDashboardAPIView,
    PublicAppSettingsAPIView,
    RejectCompanyAPIView,
    SavedItemsAPIView,
    SubCategoryCreateAPIView,
    SubCategoryDetailAPIView,
    ToggleCompanyStatusAPIView,
    ToggleFeaturedAPIView,
    ToggleFlyerAPIView,
    ToggleProductAPIView,
    ToggleSaveAPIView,
    ToggleUserStatusAPIView,
    UserDashboardAPIView,
    UserNavbarAPIView,
    UserProfileAPIView,
    FlyerReviewListAPIView,
    FlyerReviewCreateUpdateAPIView,
)
from deals_app.auth_views import LoginAPIView, LogoutAPIView, RegisterAPIView



urlpatterns = [
    path("home/", HomePageAPIView.as_view(), name="home-api"),
    path("settings/public/", PublicAppSettingsAPIView.as_view()),
    path("auth/login/", LoginAPIView.as_view(), name="login-api"),
    path("auth/register/", RegisterAPIView.as_view(), name="register-api"),
    path("auth/logout/", LogoutAPIView.as_view(), name="logout-api"),
    # Admin
    path("auth/user/me/", CurrentUserAPIView.as_view()),
    path("auth/admin/dashboard/", AdminDashboardAPIView.as_view()),
    path("auth/admin/companies/", AdminCompanyListCreateAPIView.as_view()),
    path("auth/admin/companies/<int:pk>/", AdminCompanyDetailAPIView.as_view()),
    path("auth/admin/companies/<int:pk>/toggle/", ToggleCompanyStatusAPIView.as_view()),
    path("auth/admin/users/", AdminUserListCreateAPIView.as_view()),
    path("auth/admin/users/<int:pk>/", AdminUserDetailAPIView.as_view()),
    path("auth/admin/users/<int:pk>/toggle/", ToggleUserStatusAPIView.as_view()),
    path("auth/admin/settings/", AppSettingsAPIView.as_view()),
    path("auth/admin/profile/", AdminProfileAPIView.as_view()),
    path("auth/admin/flyers/", AdminFlyerListAPIView.as_view()),
    path("auth/admin/flyers/<int:pk>/toggle/", ToggleFlyerAPIView.as_view()),
    path("auth/admin/flyers/<int:pk>/delete/", DeleteFlyerAPIView.as_view()),
    path("auth/admin/products/", AdminProductListAPIView.as_view()),
    path("auth/admin/products/<int:pk>/toggle/", ToggleProductAPIView.as_view()),
    path("auth/admin/products/<int:pk>/feature/", ToggleFeaturedAPIView.as_view()),
    path("auth/admin/products/<int:pk>/delete/", DeleteProductAPIView.as_view()),
    path("auth/admin/categories/", AdminCategoryAPIView.as_view()),
    path("auth/admin/categories/<int:pk>/", CategoryDetailAPIView.as_view()),
    path("auth/admin/subcategories/", SubCategoryCreateAPIView.as_view()),
    path("auth/admin/subcategories/<int:pk>/", SubCategoryDetailAPIView.as_view()),
    # company
    path("auth/user/company/", CompanyCurrentUserAPIView.as_view()),
    path("auth/company/dashboard/", CompanyDashboardAPIView.as_view()),
    path("auth/company/products/", CompanyProductListAPIView.as_view()),
    path("auth/company/flyers/", CompanyFlyerListAPIView.as_view()),
    path("auth/company/profile/update/", CompanyProfileUpdateAPIView.as_view()),
    path("auth/company/flyers/<int:pk>/update/", CompanyFlyerUpdateAPIView.as_view()),
    path("auth/company/flyers/<int:pk>/delete/", CompanyFlyerDeleteAPIView.as_view()),
    path("auth/company/flyers/<int:pk>/toggle/", CompanyFlyerToggleAPIView.as_view()),
    path("auth/company/flyers/create/", CompanyFlyerCreateAPIView.as_view()),
    path("auth/company/flyers/reviews/", CompanyFlyerReviewsAPIView.as_view()),
    path("auth/company/products/create/", CompanyProductListCreateAPIView.as_view()),
    path("auth/company/products/<int:pk>/update/", CompanyProductUpdateAPIView.as_view()),
    path("auth/company/products/<int:pk>/delete/", CompanyProductDeleteAPIView.as_view()),
    path("auth/company/products/<int:pk>/toggle/", CompanyProductToggleAPIView.as_view()),
    # User
    path("auth/user/navbar/", UserNavbarAPIView.as_view()),
    path("auth/user/dashboard/", UserDashboardAPIView.as_view()),
    path("auth/user/save-toggle/", ToggleSaveAPIView.as_view()),
    path("auth/user/saved-items/", SavedItemsAPIView.as_view(), name="saved-items"),
    path("auth/user/profile/", UserProfileAPIView.as_view()),
    path("auth/company-request/", CompanyRequestCreateAPIView.as_view()),
    path("auth/admin/company-requests/", CompanyRequestListAPIView.as_view()),
    path("auth/admin/company-approve/<int:pk>/", ApproveCompanyAPIView.as_view()),
    path("auth/admin/company-reject/<int:pk>/", RejectCompanyAPIView.as_view()),

    path("flyers/<int:flyer_id>/reviews/", FlyerReviewListAPIView.as_view()),
    path("flyers/<int:flyer_id>/reviews/create/", FlyerReviewCreateUpdateAPIView.as_view()),

]
