# Generated by Django 5.0.6 on 2026-04-13 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productreview",
            name="flyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="deals_app.dealflyer",
            ),
        ),
    ]
