# Generated by Django 5.0.6 on 2026-04-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals_app", "0002_alter_productreview_flyer"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productreview",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="productreview",
            constraint=models.UniqueConstraint(
                condition=models.Q(("flyer__isnull", False)),
                fields=("user", "flyer"),
                name="unique_user_flyer_review",
            ),
        ),
    ]
