# Generated by Django 5.0.6 on 2026-04-14 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals_app", "0003_alter_productreview_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedproduct",
            name="flyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_products",
                to="deals_app.dealflyer",
            ),
        ),
    ]
