# Generated by Django 5.0.6 on 2026-04-14 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals_app", "0004_savedproduct_flyer"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedproduct",
            name="saved_flyer_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="savedproduct",
            name="saved_product_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="savedproduct",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_by_users",
                to="deals_app.product",
            ),
        ),
    ]
