# Generated by Django 5.0.6 on 2026-04-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals_app", "0005_savedproduct_saved_flyer_count_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="savedproduct",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="savedproduct",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="savedproduct",
            constraint=models.UniqueConstraint(
                condition=models.Q(("product__isnull", False)),
                fields=("user", "product"),
                name="unique_user_product",
            ),
        ),
        migrations.AddConstraint(
            model_name="savedproduct",
            constraint=models.UniqueConstraint(
                condition=models.Q(("flyer__isnull", False)),
                fields=("user", "flyer"),
                name="unique_user_flyer",
            ),
        ),
    ]
