# Generated by Django 5.0.6 on 2026-04-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals_app", "0007_companyrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dealflyer",
            name="end_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="dealflyer",
            name="start_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AddConstraint(
            model_name="dealflyer",
            constraint=models.CheckConstraint(
                check=models.Q(("start_date__lte", models.F("end_date"))),
                name="deal_start_before_end",
            ),
        ),
    ]
