# Generated by Django 5.0.6 on 2026-04-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "deals_app",
            "0008_alter_dealflyer_end_date_alter_dealflyer_start_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dealflyer",
            name="category_type",
            field=models.CharField(
                choices=[
                    ("supermarket", "Supermarkets"),
                    ("restaurant", "Restaurants"),
                    ("health", "Health & Clinics"),
                    ("beauty", "Beauty & Spas"),
                    ("fashion", "Fashion"),
                    ("sports", "Sports"),
                    ("home", "Home & Garden"),
                    ("online", "Online Deals"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
