# Generated by Django 5.0.6 on 2026-04-16 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="marketplace/categories/"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_negotiable", models.BooleanField(default=True)),
                (
                    "condition",
                    models.CharField(
                        choices=[("new", "New"), ("used", "Used")], max_length=10
                    ),
                ),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="marketplace.category",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_carts",
                        to="marketplace.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="marketplace/products/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="marketplace.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="marketplace.product",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="marketplace/users/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["title"], name="marketplace_title_506a7b_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category"], name="marketplace_categor_0fd450_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["price"], name="marketplace_price_34d50e_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["city"], name="marketplace_city_0d3459_idx"),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(fields=["user"], name="marketplace_user_id_d5505e_idx"),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["product"], name="marketplace_product_c92050_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cart",
            unique_together={("user", "product")},
        ),
        migrations.AddIndex(
            model_name="productrequest",
            index=models.Index(fields=["buyer"], name="marketplace_buyer_i_fb6884_idx"),
        ),
        migrations.AddIndex(
            model_name="productrequest",
            index=models.Index(
                fields=["seller"], name="marketplace_seller__2703e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productrequest",
            index=models.Index(fields=["status"], name="marketplace_status_572ca3_idx"),
        ),
        migrations.AddIndex(
            model_name="productrequest",
            index=models.Index(
                fields=["seller", "status"], name="marketplace_seller__7e1203_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productrequest",
            index=models.Index(
                fields=["buyer", "status"], name="marketplace_buyer_i_99fd7f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productrequest",
            constraint=models.UniqueConstraint(
                fields=("product", "buyer"), name="unique_product_request"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["city"], name="marketplace_city_11cd1c_idx"),
        ),
    ]
