# Generated by Django 5.0.6 on 2026-04-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productrequest",
            name="is_read",
            field=models.BooleanField(default=0),
        ),
    ]
