# Generated by Django 5.0.6 on 2026-04-17 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_productrequest_is_read"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cart",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="view_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="productrequest",
            name="is_read",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["view_count"], name="marketplace_view_co_3a181a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-created_at"], name="marketplace_created_19f3ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productrequest",
            index=models.Index(
                fields=["seller", "is_read"], name="marketplace_seller__1f870e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productrequest",
            index=models.Index(
                fields=["buyer", "is_read"], name="marketplace_buyer_i_9a0067_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["-created_at"], name="marketplace_created_f7cfa7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                fields=("user", "product"), name="unique_cart_item"
            ),
        ),
    ]
